name: Prerelease
on: release
jobs:
  prerelease-job:
    name: Prerelease Job
    runs-on: ubuntu-latest
    steps:
      - if: github.event.action == 'prereleased'
        run: echo hello
    steps:
      - if: github.event.action == 'published'
        run: echo bye
